

include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_shadowing_type_parameters: false
    await_only_futures: true
    non_constant_identifier_names: false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    avoid_unnecessary_containers: false






